[package]
name = "bin"
version = "0.1.0"
authors = ["Ryan Faulhaber <ryf@sent.as>"]
edition = "2018"

[[bin]]
name = "dial-bin"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dial = { path = "../dial" }
rustyline = "6.3.0"
thiserror = "1.0"
anyhow = "1.0"