[package]
name = "dial"
version = "0.1.0"
authors = ["Ryan Faulhaber <faulhaberryan@gmail.com>"]
edition = "2018"

[dependencies]
pest = "^2.1.0"
pest_derive = "^2.1.0"
rustyline = "^3.0.0"
log = "^0.4.0"
env_logger = "^0.6.1"