[package]
name = "std"
version = "0.1.0"
authors = ["Ryan Faulhaber <ryf@sent.as>"]
edition = "2018"

[lib]
name = "dial_std"
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
